### ISSUE TITLE
Возможность отключить выбор карты внутри PayFormActivity

### ISSUE THREAD

**Issue by revers-back** [TinkoffCreditSystems/tinkoff-asdk-android#19]
Иногда нужно использовать PayFormActivity без возможности перевыбирать карту, только для использования данных новой карты

**Comment by revers-back** [comment]
Достаточно на этот элемент просто накинуть стиль. Можно будет скрывать его полностью

**Comment by revers-back** [comment]
Так и с каким результатом закрыли? Будет такая возможность в следующей версии?

**Comment by tralfamadore** [comment]
Посчитал что предыдущей коммент является ответом, тк уже сейчас можно накинуть такой стиль)
