### ISSUE TITLE
При переходе на версию 1.3.4 пропал класс NfcCardScanActivity

### ISSUE THREAD

**Issue by btow** [TinkoffCreditSystems/tinkoff-asdk-android#25]
После вставки в проект файлов реализации на новом SDK 1.3.4 в манифесте имя этого класса в инструкции
`        <activity
            android:name="ru.tinkoff.acquiring.sdk.nfc.NfcCardScanActivity"
            android:screenOrientation="portrait" />
`
подсвечивается красным.
Чем его заменить?

**Comment by Vittt2008** [comment]
`ru.tinkoff.acquiring.sdk.nfc.AsdkNfcScanActivity`
