### ISSUE TITLE
Отсутствует ввод данных о карте при помощи камеры 

### ISSUE THREAD

**Issue by btow** [TinkoffCreditSystems/tinkoff-asdk-android#26]
При нажатии кнопки на экране:

![input_card_data](https://user-images.githubusercontent.com/22589346/38498984-a3a1e74c-3c1f-11e8-8d06-024c6685a556.jpg)

Вместо диалога выбора способа ввода данных сразу открывается экран для ввода при помощи NFC:

![input_card_data_nfc](https://user-images.githubusercontent.com/22589346/38499067-e4f2e64c-3c1f-11e8-883a-d5e55214e65f.jpg)

Доступ к камере в манифесте открыт:

`
    <uses-permission android:name="android.permission.CAMERA" />
    <uses-feature android:name="android.hardware.camera" />
    <uses-feature android:name="android.hardware.camera.autofocus" />
    <uses-feature
        android:name="android.hardware.camera.flash"
        android:required="false" />
`

Почему sdk не выводит диалог выбора варианта сканирования?

**Comment by Vittt2008** [comment]
Так как вы используете версию выше 1.3.1, то прочитайте README в соответствующей ветке. 
[README 1.3.3](https://github.com/TinkoffCreditSystems/tinkoff-asdk-android/tree/1.3.3)
Также посмотрите [Changelogs](https://github.com/TinkoffCreditSystems/tinkoff-asdk-android/wiki/Changelogs), там конкретно указано, что модуль сканирования вынесен в отдельную зависимость, которая предоставляет базовую реализацию CameraCardIOScanner. При желании можете указать свою.
Если её не подключить, то по умолчанию будет открываться сканирование карты с помощью  NFC.
Пример использования:
```Java
PayFormActivity
        .init("TERMINAL_KEY", "PASSWORD", "PUBLIC_KEY") // данные продавца
        .prepare(//TODO params)
        .setCustomerKey("CUSTOMER_KEY")     // уникальный ID пользователя для сохранения данных его карты
        .setReceipt(receipt)
        .setData(dataMap)
        .setTheme(themeId)
        .setChargeMode(chargeMode)
        .setCameraCardScanner(new CameraCardIOScanner()))
        .startActivityForResult(this, REQUEST_CODE_PAYMENT);
```
