### ISSUE TITLE
Сделать SECURE_LOGOS не обязательным пареметром для setDesignConfiguration

### ISSUE THREAD

**Issue by mounlion** [TinkoffCreditSystems/tinkoff-asdk-android#34]
Сделал pull request https://github.com/TinkoffCreditSystems/tinkoff-asdk-android/pull/33

**Comment by al-dr** [comment]
Отображение этих логотипов пользователю является обязательным на экранах, где вводятся данные карты. На ios будет доработка, чтобы сделать их тоже обязательными.

**Comment by mounlion** [comment]
Спасибо за ответ
