### ISSUE TITLE
В http(s) нотификации не приходят параметры из setData

### ISSUE THREAD

**Issue by kmityakov** [TinkoffCreditSystems/tinkoff-asdk-android#41]
Запускаю PayFormActivity, передав в нее параметры при создании с помощью метода setData. 
В логах вижу, что при создании платежа (https://securepay.tinkoff.ru/v2/Init) параметры из setData присутсвуют в запросе. Однако, при получении нотификации по http(s), этих параметров нет, хотя согласно документации должны быть (https://oplata.tinkoff.ru/landing/develop/notifications/parametres - параметр DATA)
Для проверки использую тестовый терминал.

С чем может быть связана описанная проблема?

**Comment by kmityakov** [comment]
В личном кабинете написали в поддержку, после чего данный функционал был включен.
Хорошо бы где-то указать в документации, что по дефолту он не работает.

**Comment by sehrun** [comment]
Спасибо за пост, это единственное что гугл выдал. 
Параметр DATA [тут](https://oplata.tinkoff.ru/develop/api/notifications/setup-request/) указанный так и не приходит по-умолчанию. Фактически документация неправильная. Параметр начинает приходить через множество часов после обращения в поддержку (т.е. быстро не настроить).
Более того саму [эту ](https://oplata.tinkoff.ru/develop/api/notifications/setup-request/) документацию можно найти лишь через повторный запрос в гугл. Так как в [описании подключения нотификаций](https://www.tinkoff.ru/kassa/develop/api/notifications/) ссылки на неё нет.

**Comment by sehrun** [comment]
Спасибо за пост, это единственное что гугл выдал. 
Параметр DATA [тут](https://oplata.tinkoff.ru/develop/api/notifications/setup-request/) указанный так и не приходит по-умолчанию. Фактически документация неправильная. Параметр начинает приходить по прошествии множества часов после обращения в поддержку (т.е. быстро не настроить).
