### ISSUE TITLE
Ошибка "null: null" при недостатке средств

### ISSUE THREAD

**Issue by androyell** [TinkoffCreditSystems/tinkoff-asdk-android#6]
Если на карте недостаточно средств, SDK возвращает исключение с текстом "null: null" в `ru.tinkoff.acquiring.sdk.OnPaymentListener#onError`

**Comment by tralfamadore** [comment]
https://github.com/TinkoffCreditSystems/tinkoff-asdk-android/commit/e56ce4d60dd93ba9b4d98c59befd0e5a18c491ef
