### ISSUE TITLE
Ошибка при оплате Google Pay

### ISSUE THREAD

**Issue by MrOlolo** [TinkoffCreditSystems/tinkoff-asdk-android#63]
При попытке оплатить с помощью GPay, PayFormActivity возвращает ошибку:
`ru.tinkoff.acquiring.sdk.AcquiringSdkException: Parameters are invalid: Card data decrypting error`. Иногда возвращает ошибку по пустом PAN-полю

**Comment by mercuriy94** [comment]
У меня аналогичная проблема.
Пытаюсь использовать PayFormActivity с передачей параметров для Google Pay (GooglePayParams) с WalletConstants.ENVIRONMENT_TEST.
В логах на запрос [https://securepay.tinkoff.ru/v2/FinishAuthorize](url) возвращается ошибка:
{"Success":false,"ErrorCode":"9999","Message":"Неверные параметры.","Details":"Ошибка шифрования карточных данных."}

Попробовал зайти с другого конца, без формы PayFormActivity, а с использованием модуля Payment, так как описано в данном вопросе - https://github.com/TinkoffCreditSystems/tinkoff-asdk-android/issues/61#issuecomment-513140801

` 

        val token = PaymentData.getFromIntent(data)?.paymentMethodToken?.token ?: return
        tinkoffPay.pay(token , paymentData)
`


То есть я самостоятельно получаю GPay token и передаю в параметры метода `TinkoffPay.pay` 
и согласно логам получаю аналогичный результат с кодом ошибки 9999.

Отмечу, что если делать оплату   `TinkoffPay.pay`  c параметрами карты 

` 

        val cardData = CardData("4300000000000777", "11/22", "111")
        tinkoffPay.pay(cardData , paymentData)
`

То результат оплаты возвращается успешным. 

Исходя из выше описанного, моё предположение, что происходит какая-то ошибка во время
 декодирования GPay токена.

**Comment by MrOlolo** [comment]
Да, проблема при декодировании) Гугл в тестовой среде шлет "плохой" токен, чтобы не списывались деньги, а тинькофф не обрабатывает данный кейс. Когда получил от гугла доступ к проду все заработало. В тех. поддержке Тинькофф сказали, что для GP нужно использовать другой терминал, но у меня с ним тоже ничего не работало.

**Comment by DmitryVdovichencko** [comment]
> Да, проблема при декодировании) Гугл в тестовой среде шлет "плохой" токен, чтобы не списывались деньги, а тинькофф не обрабатывает данный кейс. Когда получил от гугла доступ к проду все заработало. В тех. поддержке Тинькофф сказали, что для GP нужно использовать другой терминал, но у меня с ним тоже ничего не работало.

Привет. Тоже столкнулись с этой проблемой. Хотел уточнить: как получить доступ к проду от гугла? Просто я так понял что приложение нужно направить на аппрув в Google для того чтобы получить доступ к проду. Они с этой проблемой его аппрувят?

**Comment by MrOlolo** [comment]
> > Да, проблема при декодировании) Гугл в тестовой среде шлет "плохой" токен, чтобы не списывались деньги, а тинькофф не обрабатывает данный кейс. Когда получил от гугла доступ к проду все заработало. В тех. поддержке Тинькофф сказали, что для GP нужно использовать другой терминал, но у меня с ним тоже ничего не работало.
> 
> Привет. Тоже столкнулись с этой проблемой. Хотел уточнить: как получить доступ к проду от гугла? Просто я так понял что приложение нужно направить на аппрув в Google для того чтобы получить доступ к проду. Они с этой проблемой его аппрувят?

Привет. У меня никаких проблем не возникло. Проверять покупку они будут уже на проде. А в первый апрув гугл смотрит только на соответствие гайдлайнам GooglePay

**Comment by DmitryVdovichencko** [comment]
> > > Да, проблема при декодировании) Гугл в тестовой среде шлет "плохой" токен, чтобы не списывались деньги, а тинькофф не обрабатывает данный кейс. Когда получил от гугла доступ к проду все заработало. В тех. поддержке Тинькофф сказали, что для GP нужно использовать другой терминал, но у меня с ним тоже ничего не работало.
> > 
> > 
> > Привет. Тоже столкнулись с этой проблемой. Хотел уточнить: как получить доступ к проду от гугла? Просто я так понял что приложение нужно направить на аппрув в Google для того чтобы получить доступ к проду. Они с этой проблемой его аппрувят?
> 
> Привет. У меня никаких проблем не возникло. Проверять покупку они будут уже на проде. А в первый апрув гугл смотрит только на соответствие гайдлайнам GooglePay

Большое спасибо за полезную информацию. :+1: Будем идти по этому пути :pray:

**Comment by DmitryVdovichencko** [comment]
> > > Да, проблема при декодировании) Гугл в тестовой среде шлет "плохой" токен, чтобы не списывались деньги, а тинькофф не обрабатывает данный кейс. Когда получил от гугла доступ к проду все заработало. В тех. поддержке Тинькофф сказали, что для GP нужно использовать другой терминал, но у меня с ним тоже ничего не работало.
> > 
> > 
> > Привет. Тоже столкнулись с этой проблемой. Хотел уточнить: как получить доступ к проду от гугла? Просто я так понял что приложение нужно направить на аппрув в Google для того чтобы получить доступ к проду. Они с этой проблемой его аппрувят?
> 
> Привет. У меня никаких проблем не возникло. Проверять покупку они будут уже на проде. А в первый апрув гугл смотрит только на соответствие гайдлайнам GooglePay

Привет) Еще раз огромное спасибо за инфу) Аппрув прошли получили доступ к проду. Хотел уточнить: после того как получили рабочий токен проверки покупок прошли норм? Просто уже который день, бьюсь в общении с тп Тинькофф, пытаясь добиться вразумительного ответа: почему не проходит проверку авторизации при завершении платежа. И пока все как то не очень(

**Comment by MrOlolo** [comment]
> > > > Да, проблема при декодировании) Гугл в тестовой среде шлет "плохой" токен, чтобы не списывались деньги, а тинькофф не обрабатывает данный кейс. Когда получил от гугла доступ к проду все заработало. В тех. поддержке Тинькофф сказали, что для GP нужно использовать другой терминал, но у меня с ним тоже ничего не работало.
> > > 
> > > 
> > > Привет. Тоже столкнулись с этой проблемой. Хотел уточнить: как получить доступ к проду от гугла? Просто я так понял что приложение нужно направить на аппрув в Google для того чтобы получить доступ к проду. Они с этой проблемой его аппрувят?
> > 
> > 
> > Привет. У меня никаких проблем не возникло. Проверять покупку они будут уже на проде. А в первый апрув гугл смотрит только на соответствие гайдлайнам GooglePay
> 
> Привет) Еще раз огромное спасибо за инфу) Аппрув прошли получили доступ к проду. Хотел уточнить: после того как получили рабочий токен проверки покупок прошли норм? Просто уже который день, бьюсь в общении с тп Тинькофф, пытаясь добиться вразумительного ответа: почему не проходит проверку авторизации при завершении платежа. И пока все как то не очень(

После получения апрува и смены терминала на рабочий с тестового. Всё работало. Чекали на реальной карте - добавили тестовый товар стоимостью 1 рубль

**Comment by DmitryVdovichencko** [comment]
@MrOlolo  еще раз спасибо за помощь, разобрались все получилось))

**Comment by HappyCodingLover** [comment]
@MrOlolo I implement google pay with Tinkoff in my react native app.
GPay button is showing in Huawei Phone, but NOT showing in Google Pixel phone.
Can you help me?

**Comment by MrOlolo** [comment]
> @MrOlolo I implement google pay with Tinkoff in my react native app.
> GPay button is showing in Huawei Phone, but NOT showing in Google Pixel phone.
> Can you help me?

Hi. No idea. And i doubt that smb can help u without additional info (for example - Android version; Can u pay with GPay at another apps; What u see at logs; Mb minimal code example of implementation for tests and etc)
