### ISSUE TITLE
ClassCastException: java.lang.Long cannot be cast to ru.tinkoff.acquiring.sdk.Money

### ISSUE THREAD

**Issue by DJOxid** [TinkoffCreditSystems/tinkoff-asdk-android#7]
Походу не правильный аргумент в методе
`PayFormStarter prepare(String orderId, Long amount, boolean reccurentPayment)`.
А в классе `EnterCardFragment` забирается значение следующим образом
`final Money amount = (Money) intent.getSerializableExtra(PayFormActivity.EXTRA_AMOUNT);`

Как результат ошибка привидения типов.

**Comment by tralfamadore** [comment]
Исправлено в 1.1.2, релиз до 20 февраля.
